language: d

sudo: false

d:
  - dmd-2.080.1
  - dmd-2.079.1
  - dmd-2.078.3
  - dmd-2.077.1
  - dmd-2.076.1
  - ldc-1.9.0
  - ldc-1.8.0
  - ldc-1.7.0
  - ldc-1.6.0
  
matrix:
  allow_failures:
  - d: dmd-nightly
  - d: dmd-beta
  - d: dmd
  - d: ldc-beta
  - d: ldc

script:
  - dub test --compiler=$DC || exit 1
